name = "baan-ing-landing"
compatibility_date = "2024-11-01"
pages_build_output_dir = "./dist"
assets = { directory = "./dist" }

[env.production]
routes = [
  { pattern = "baan.ing", custom_domain = true },
  { pattern = "www.baan.ing", custom_domain = true }
]
